config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  scope module: :public do
    root to: "homes#top"
    delete "car_items/destroy_all" => "car_items#destroy_all"
    post 'orders/confirm' => "orders#confirm"
    get "orders/thanks" => "orders#thanks"

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :car_items, only: [:index, :update, :destroy, :create]

    get "about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/check" => "customers#check"
    patch "customers/withdraw" => "customers#withdraw"
  end
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :car_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_name
    last_name + '' + first_name
  end

  def full_name_kana
    last_name_kana + '' + first_name_kana
  end

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end
  
  def customer_address_display
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @customer_pages = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update!(customer_params)
    redirect_to admin_customer_path(customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :address, :postal_code, :telephone_number, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <label class="h4 bg-light px-4">
    <%= @customer.full_name %>さんの会員情報編集
  </label>
  <dvi class="row mb-2">
    <div class="col-lg-10">
      <%= form_with model: @customer, url: admin_customer_path(@customer), local:true do |f| %>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= f.text_field :last_name, class:"mr-4" %> <%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= f.text_field :last_name_kana, class:"mr-4" %> <%= f.text_field :first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th>販売ステータス</th> <!--ラジオボックスで作成-->
      　    <td>
      　      <%= f.radio_button :is_active, true %>有効
      　　    <%= f.radio_button :is_active, false %>退会
      　　  </td>
          </tr>
          <tr>
            <td></td>
            <td><%= f.submit "変更を保存", class: 'btn btn-success' %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row mb-2">
    <div class="col-lg-2"></div>
    <div class="col-lg-10">
      <label class="h4 bg-light px-4">会員一覧</label>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <table class="table table shadow-sm">
        <thead class="bg-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
        <% @customers.each do |f| %>
          <tr>
            <td><%= f.id %></td>
            <td><%= link_to f.full_name, admin_customer_path(f) %></td>
            <td><%= f.email %></td>
            <td><%= f.customer_status %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-lg-2"></div>
  </div>
  <div class="row mb-2">
    <div class="col-lg-5"></div>
    <div class="col-lg-7">
      <%= paginate @customer_pages %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <label class="h4 bg-light px-4">
    <%= @customer.full_name %>さんの会員詳細
  </label>
  <div class="row mb-2">
    <div class="col-lg-6">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @customer.full_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= @customer.full_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th>
              会員ステータス
            </th>
            <td>
              <% if @customer.is_active == true %>
                <p class="text-success">有効</p>
              <% else %>
                <p class="text-muted">退会</p>
              <% end %>
            </td>
          </tr>
          <tr>
            <td><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "注文履歴一覧を見る", order_path, class:"btn btn-primary" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>