config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  scope module: :public do
    root to: "homes#top"
    delete "car_items/destroy_all" => "car_items#destroy_all"
    post 'orders/confirm' => "orders#confirm"
    get "orders/thanks" => "orders#thanks"

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :car_items, only: [:index, :update, :destroy, :create]

    get "about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/check" => "customers#check"
    patch "customers/withdraw" => "customers#withdraw"
  end
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  validates :address, presence: true
  validates :payment_method, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4}

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    # # @total_price = 0
    # # @order_details.each do |order_detail|
    # #   @total_price += (order_detail.item.price * 1.1 * order_detail.amount).floor
    # end
  end

  def update
    order = Order.find(params[:id])
    order_details = order.order_details
    order.update(order_params)

    if order.status == "confirm_payment"
      order_details.update_all(making_status: "waiting_manufacture")
    end
		redirect_to admin_order_path(order.id)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <label class="h4 bg-light px-4">注文履歴詳細</label>
  <div class="row mb-2">

    <div class="col-lg-6">
      <table class="table table-borderless">
        <tr>
          <th>購入者</th>
          <td><%= link_to (@order.customer.last_name + ' ' + @order.customer.first_name), admin_customer_path(@order.customer.id) %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url:admin_order_path(@order), method: :patch do |order| %>
              <%= order.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
              <%= order.submit '更新', class:"btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>

  </div>

  <div class="row mb-2">

    <div class="col-lg-8">
      <table class="table table shadow-sm">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.item.price * 1.1).floor.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= ((order_detail.item.price * 1.1) * order_detail.amount).floor.to_s(:delimited) %></td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |makes| %>
              <td><%= makes.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %></td>
              <td><%= makes.submit '更新', class:"btn btn-success" %></td>
            <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-lg-4 d-flex align-items-end mb-2">
      <table>
        <tr>
          <th>商品合計</th>
          <td><%= number_to_currency(@order.total_payment - @order.shipping_cost, unit:"円") %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= number_to_currency(@order.shipping_cost, unit:"円") %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= number_to_currency(@order.total_payment, unit:"円") %></td>
        </tr>
      </table>
    </div>

  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>