config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :order_details, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  scope module: :public do
    root to: "homes#top"
    delete "car_items/destroy_all" => "car_items#destroy_all"
    post 'orders/confirm' => "orders#confirm"
    get "orders/thanks" => "orders#thanks"

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :car_items, only: [:index, :update, :destroy, :create]

    get "about" => "homes#about", as: "about"
    get "customers/mypage" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    get "customers/check" => "customers#check"
    patch "customers/withdraw" => "customers#withdraw"
  end
  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
    
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <label class="h4 bg-light px-4">ジャンル編集</label>

  <div class="row">
    <div class="col-lg-10">
      <div class="form mt-5 mb-5">
        <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
          <%= f.label :ジャンル名, class:"mr-5" %>
          <%= f.text_field :name %>
          <%= f.submit '変更を保存', class:"btn btn-success ml-5 px-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <label class="h4 bg-light mb-5 px-4">ジャンル一覧・追加</label>
  <div class="row">
    <div class="col-lg-10">
      <%= form_with model: @genre, url: admin_genres_path do |f| %>
        <%= f.label :ジャンル名, class:"mr-5" %>
        <%= f.text_field :name %>
        <%= f.submit '新規登録', class:"btn btn-success ml-5" %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <table class="table shadow-sm mt-5">
        <thead class="bg-light">
          <th>ジャンル</th>
          <th colspan="1"></th>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>